name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      name: Add Stack binaries to PATH

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}

    # Skip `make dependencies` in CI.
    # This probably isn't needed with Stack.
    # Skipping it saves about 1.5 min on the build.
    - run: make build
    - run: make tests