name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Skip `make dependencies` in CI.
    # This probably isn't needed with Stack.
    # Skipping it saves about 1.5 min on the build.
    - run: make build
    - run: make tests