name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: echo "$HOME/.local/bin" >> $GITHUB_PATH
      name: Add Stack binaries to PATH

    - uses: actions/cache@v2
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}

    - run: make dependencies
    - run: make build
    - run: make tests